# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accordion',
            old_name='acordeon_id',
            new_name='acordion_id',
        ),
    ]
