# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0002_auto_20171019_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='acordion_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id del acordeon'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
