# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0005_auto_20171020_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accordion',
            old_name='panel',
            new_name='parent',
        ),
    ]
