# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0006_auto_20171020_0132'),
        ('accordion', '0005_auto_20171020_0116'),
    ]

    operations = [
    ]
