# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0007_merge_20171020_0325'),
        ('accordion', '0002_project'),
    ]

    operations = [
    ]
