# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0008_merge_20171020_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='content_style',
            field=models.TextField(blank=True, null=True, verbose_name='Estilos del contenido'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='height',
            field=models.CharField(blank=True, default='30', max_length=50, null=True, verbose_name='Alto (px)'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='style',
            field=models.TextField(blank=True, null=True, verbose_name='Estilos generales'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='title_style',
            field=models.TextField(blank=True, null=True, verbose_name='Estilos del Título'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='width',
            field=models.CharField(blank=True, default='100', max_length=50, null=True, verbose_name='Ancho (%)'),
        ),
    ]
