# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0009_auto_20171020_2155'),
        ('accordion', '0009_auto_20171022_2323'),
    ]

    operations = [
    ]
