# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0011_auto_20171031_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='border_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color del borde'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='border_radius',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Radio del borde (px)'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='content_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color del contenido'),
        ),
    ]
