# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0012_auto_20171101_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='acordion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
