# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minesweep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minesweep_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id del minesweep')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('width', models.CharField(blank=True, default='50', max_length=50, null=True, verbose_name='Ancho (%)')),
                ('height', models.CharField(blank=True, default='30', max_length=50, null=True, verbose_name='Alto (px)')),
            ],
        ),
    ]
