# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweep',
            name='content_style',
            field=models.TextField(blank=True, null=True, verbose_name='Estilos del contenido'),
        ),
    ]
