# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0002_minesweep_content_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweep',
            name='parent',
            field=models.TextField(blank=True, null=True, verbose_name='Elemento a agregar el tooltip'),
        ),
    ]
