# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0003_minesweep_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minesweep',
            name='parent',
        ),
        migrations.AddField(
            model_name='minesweep',
            name='tooltip',
            field=models.TextField(blank=True, null=True, verbose_name='Información del tooltip'),
        ),
    ]
