# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0004_auto_20171024_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweep',
            name='tooltip_style',
            field=models.TextField(blank=True, null=True, verbose_name='Estilos del tooltip'),
        ),
    ]
