# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0005_minesweep_tooltip_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweep',
            name='tooltip_side',
            field=models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('right', 'right'), ('left', 'left')], default='arriba', max_length=6),
        ),
    ]
