# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0006_minesweep_tooltip_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweep',
            name='tooltip_side',
            field=models.CharField(choices=[('top', 'arriba'), ('bottom', 'abajo'), ('right', 'derecha'), ('left', 'izquierda')], default='arriba', max_length=6, verbose_name='Lado del tootlip'),
        ),
    ]
