# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweep', '0007_auto_20171027_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweep',
            name='border_color',
            field=models.TextField(blank=True, null=True, verbose_name='Color del borde'),
        ),
        migrations.AddField(
            model_name='minesweep',
            name='border_radius',
            field=models.TextField(blank=True, null=True, verbose_name='Radio del borde'),
        ),
        migrations.AddField(
            model_name='minesweep',
            name='border_style',
            field=models.TextField(blank=True, null=True, verbose_name='Definir tipo de borde'),
        ),
        migrations.AddField(
            model_name='minesweep',
            name='content_color',
            field=models.TextField(blank=True, null=True, verbose_name='Color del contenido'),
        ),
        migrations.AddField(
            model_name='minesweep',
            name='style',
            field=models.TextField(blank=True, null=True, verbose_name='Extra CSS'),
        ),
        migrations.AlterField(
            model_name='minesweep',
            name='width',
            field=models.CharField(blank=True, default='100', max_length=50, null=True, verbose_name='Ancho (%)'),
        ),
    ]
