# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('timer', models.IntegerField(blank=True, default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto', models.BooleanField(default=False)),
                ('circular', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='carouselImages/')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrusel.Carousel')),
            ],
        ),
    ]
