# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('nItemsOnPage', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
