# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import servecaptcha.utils.random_string


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_id', models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True)),
                ('answer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True)),
                ('private_key', models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='generatedcaptcha',
            name='keypair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servecaptcha.KeyPair'),
        ),
    ]
