# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import servecaptcha.utils.random_string


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True)),
                ('private_key', models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
